name: Snyk

on:
  push:
    branches: [ master ]

jobs:
  check-vulnerabilities:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Snyk monitor - Check for vulnerabilities
      uses: snyk/actions/scala@master
      with:
        command: monitor
        args: --project-name=analytics-sdk-scala
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}