name: Snyk

on: push


jobs:
  check-vulnerabilities:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Snyk monitor - Check for vulnerabilities
      uses: snyk/actions/scala@master
      with:
        command: test
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}